version: 2
updates:
  - package-ecosystem: "npm"
    directory: "examples/aws-lambda" 
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "examples/cloudflare-workers" 
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "examples/cloudflare-workers-with-typescript" 
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "examples/cloudflare-workers-with-wrangler-1" 
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "examples/deno" 
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "examples/fastly" 
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "examples/gcp" 
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "examples/netlify" 
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "examples/netlify-edge" 
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "examples/nextjs" 
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "examples/nextjs_edge" 
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "examples/nextjs_export" 
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "examples/nodejs" 
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "examples/nodejs-18" 
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "examples/vite" 
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "examples/with-sentry" 
    schedule:
      interval: "daily"
