name = "upstash-redis-example"
type = "webpack"
account_id = "3790e4458fadef57696e9cd62e192069"
route = ''
zone_id = ''
workers_dev = true
compatibility_date = "2021-10-11"

[site]
bucket = "./dist"
entry-point = "workers-site"

[vars]
UPSTASH_REDIS_REST_URL = ""
UPSTASH_REDIS_REST_TOKEN = ""
